[package]
name = "authtown"
version = "0.0.0"
edition = "2018"

[dependencies]
argon2 = "0.3"
hyper = { version = "0.14", features = ["http1", "runtime", "server"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = "1"
tokio-postgres = "0.7"
